### ISSUE TITLE
Having location field in genes

### ISSUE THREAD

**Issue by camilogarciabotero** [BioJulia/GenomicAnnotations.jl#11]
Hi all

This package is so great! I was wondering if there is any way to fetch the `location` out of the `gbk.genes` field. Currently we can get all the fields that start with the `/` in the record:

```
gbk.genes[end]

     CDS             47738..47944
                     /db_xref="GeneID:2703534"
                     /locus_tag="lambdap79"
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="NP_597782.1"
                     /translation="MNKEQSADDPSVDLIRVKNMLNSTISMSYPDVVIACIEHKVSLE
                     AFRAIEAALVKHDNNMKDYSLVVD"
                     /note="Predicted by GeneMark"
```

I want to be able to get the location qualifier `47738..47944` encoded later as a `UnitRange{Int64}` --> `47738:47944`. Is this a feature we can have in `GenomicAnnotations` (or already have)? 

Best.

**Comment by kdyrhage** [comment]
You can use `locus(gene).position` to extract the position as a `UnitRange`. I'll consider adding an easier way to extract the position in a later version.

**Comment by camilogarciabotero** [comment]
Here is another user experimenting this:

https://discourse.julialang.org/t/how-to-get-location-of-sequence-in-genomicannotations/106731

**Comment by kdyrhage** [comment]
I've added `position(gene)` as a shorthand for `locus(gene).position`, and a section in the README about how to access the genomic position of a gene.
