### ISSUE TITLE
[Feature Request] Support for GTF format!

### ISSUE THREAD

**Issue by yang-dongxu** [BioJulia/GenomicAnnotations.jl#12]
Thank you for your hard work on this package! 
However, I have noticed that the current version does not support the basic format of GTF, while it already supports GFF3. Would it be possible to add support for GTF in the future? 
Thank you!

**Comment by kdyrhage** [comment]
Adding GTF support should be pretty straight-forward. I'll try to implement this some time in the near future, assuming I have time.

**Comment by kdyrhage** [comment]
GTF support was added in v0.4.3.
