### ISSUE TITLE
Type piracy of Base breaks package in 1.11

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/GenomicAnnotations.jl#14]
This package defines this method:
```
function Base.getproperty(genes::AbstractArray{G, 1}, name::Symbol) where {G <: AbstractGene}
   ....
```
This is piracy, since both `AbstractArray` and `AbstractGene` is implemented in Base, and breaks the package in Julia 1.11.
It may seem like it shouldn't be piracy since you explicitly only overrode `AbstractArray{<:AbstractGene}`, and this package owns `AbstractGene`. And indeed, this piracy should not be able to break code unrelated to this package.
The problem is that this package relies on existing methods for `AbstractArray` working, such as `getproperty`. When this method is overwritten, then any code that used `getproperty` for `AbstractArray{<:AbstractGene}` breaks, which includes basic Base code.

The solution is to stop pirating Base here.

**Comment by kdyrhage** [comment]
I'd rather keep the `pushproperty` overload, as removing it would break a lot of code. I've added a workaround for now.
