### ISSUE TITLE
gffstring merges multi-position features

### ISSUE THREAD

**Issue by ian-small** [BioJulia/GenomicAnnotations.jl#15]
julia> test_locus = Join([ClosedSpan(1:10), ClosedSpan(20:30)])
join(1..10,20..30)
julia> test_locus.position isa Vector
false
julia> typeof(test_locus.position)
Base.Iterators.Flatten{Base.Generator{Vector{SpanLocus{ClosedSpan}}, GenomicAnnotations.var"#24#25"}}

Thus 'if locus(gene).position isa Vector' in gffstring() fails and the feature is written to the .gff file as a single span from 1:30
This messes up CDS features with introns, for example.
Is this a bug, or am I creating my Joins wrongly?

**Comment by kdyrhage** [comment]
That is indeed a bug. I will update `gffstring` so that it works with the v0.4 loci representation.
