### ISSUE TITLE
gffstring mishandles transpliced genes

### ISSUE THREAD

**Issue by ian-small** [BioJulia/GenomicAnnotations.jl#17]
'locus(gene).strand' in gffstring assumes all positions in the locus are on the same strand, which is not true for trans-spliced genes, e.g. join(11056..11919,complement(94283..95886)) is a valid GenBank locus that can now be faithfully represented using your much-appreciated rewrite of GenomicAnnotations.Locus, but which is rendered as 
gene	11056	11919	.	+
gene	94283	95886	.	+
by GFF.gffstring()

**Comment by kdyrhage** [comment]
Thanks for bringing up these issues; I only work with prokaryotic data so I rarely encounter more complex locus descriptors myself.
