### ISSUE TITLE
minor issues with headers

### ISSUE THREAD

**Issue by ian-small** [BioJulia/GenomicAnnotations.jl#18]
Records can be created with empty headers:
Record{Gene}() = Record{Gene}("", dna"", "", Gene[], DataFrame(), false)
but 'if chrs[1].header[1:15] == "#gff-version 3\n"' in printgff() errors with an empty header (or even on one with less than 15 chars)
What's more, the equality fails even with a valid gff3 header as it should be testing for '##gff-version 3' according to the spec.
I would suggest this be changed to
if isempty(chrs[1].header)) || ~startswith(chrs[1].header, "##gff-version 3")

A question, not an issue as such. Is the ultimate intention to have some sort of cross-format Header structure for metadata? At the moment, it is not very clear how to transfer metadata from one format to another, or how to efficiently create headers from scratch.

**Comment by kdyrhage** [comment]
I did work on a parser for GenBank headers a (long) while back, and a more structured way to store the data to facilitate format-conversion, but I never had any use for it myself so I never got around to finishing it. I hope to add it eventually.
