### ISSUE TITLE
Can GenomicAnnotations.jl deal with multi-exon genes?

### ISSUE THREAD

**Issue by Xiao-Zhong** [BioJulia/GenomicAnnotations.jl#9]
Hi, I'm trying converting a genbank file to a gff with the package, however it fails. For example, one gene is as below:
Input: Screenshot 1;  https://www.ncbi.nlm.nih.gov/nuccore/7525012
![Screen Shot 2022-09-28 at 10 30 09 pm](https://user-images.githubusercontent.com/22763795/192807573-fed20b22-3e61-4b28-8008-a5a0356703c1.png)

Code: Screenshot 2
![Screen Shot 2022-09-28 at 10 36 05 pm](https://user-images.githubusercontent.com/22763795/192807808-3a581704-2804-4437-912f-a6306ff96e9e.png)

Output: Screenshot 3
<img width="1345" alt="Screen Shot 2022-09-28 at 10 37 43 pm" src="https://user-images.githubusercontent.com/22763795/192808233-2cf2d089-4fc4-45a6-8644-ded221a8bd73.png">

As shown, the CDS in the gff output doesn't have an intron between the two exons. CDS sequences extracted based on these kinds of coordinates must be wrong. Thank you!

**Comment by kdyrhage** [comment]
The intron information is stored in the `Locus`, so in theory yes. `GFF.Writer` ignores it, though. I only ever work with bacterial data so I don't know what the expected output is. Could you give an example of what you would like the result to look like?

**Comment by Xiao-Zhong** [comment]
Thanks! Please check the links below:
https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md
https://www.ncbi.nlm.nih.gov/genbank/genomes_gff/

Oh. I see. You only focused on bacterial data, single-exon genes.

**Comment by kdyrhage** [comment]
v0.3.8 fixes this.
